#!/bin/bash
echo "=========================================="
echo "     GMAIL CONFIGURATION STATUS"
echo "=========================================="
echo ""
echo "📧 Current Email Settings:"
echo "   EMAIL_USER: nghiaht28102003@gmail.com"
echo "   EMAIL_PASS: $(if [ -n "${EMAIL_PASS}" ]; then echo "***configured***"; else echo "NOT SET"; fi)"
echo "   SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}"
echo ""
echo "🔐 To enable real email sending:"
echo ""
echo "1. Go to Gmail Security Settings:"
echo "   https://myaccount.google.com/security"
echo ""
echo "2. Enable 2-Factor Authentication if not already enabled"
echo ""
echo "3. Generate App Password:"
echo "   https://myaccount.google.com/apppasswords"
echo "   - Select 'Mail' from dropdown"
echo "   - Copy the 16-character password"
echo ""
echo "4. Update .env file:"
echo "   EMAIL_PASS=your-16-character-app-password"
echo ""
echo "5. Test configuration:"
echo "   node test-email-config.js"
echo ""
echo "⚠️  SECURITY NOTE:"
echo "   - Never share your App Password"
echo "   - App Password is different from your Gmail password"
echo "   - 2FA must be enabled to create App Passwords"
echo ""
echo "📋 Alternative: Use test email service (current mode)"
echo "   - Emails sent to: https://ethereal.email/messages"
echo "   - No real emails sent to users"
echo "   - Good for development and testing"
echo ""
read -p "Press Enter to continue..."
